import 'ROS';

/***
 * This message defenition shoult be 
 * autogenerated from ROS message description language.
 * TODO: message generator implementation.
 ***/
contract UInt32 is Message {
    uint32 public data;
    function UInt32(uint32 _data) {
        data = _data;
    }
}

contract SimplePub is ROSCompatible {
    Publisher      myPub;
    
    function SampleContract() {
        // Create a new publisher by topic name and type
        myPub = mkPublisher('/gripper', 'std_msgs/UInt32');
    }

    function setPose(uint32 pose) {
        // Publish new message by received string
        myPub.publish(new UInt32(pose));
    }
}
