import 'ROS';

/***
 * This message defenition shoult be 
 * autogenerated from ROS message description language.
 * TODO: message generator implementation.
 ***/
contract MsgInt64 is Message {
    int64 public data;
    function MsgInt64(int64 _data) {
        data = _data;
    }
}

contract Integrator is MessageHandler {
    Publisher myPub;
    int64     value;
    
    function Integrator(Publisher _pub) {
        myPub = _pub;
        value = 0;
    }
    
    function incomingMessage(Message _msg) {
        value += MsgInt64(_msg).data();
        myPub.publish(new MsgInt64(value));
    }
}

contract PubSub is ROSCompatible {
    function PubSub() {
        var pub = mkPublisher("/value", "std_msgs/Int64");
        var hdl = new Integrator(pub);
        mkSubscriber("/add", "std_msgs/Int64", hdl);
    }
}
