import 'ROS';

/***
 * This message defenition shoult be 
 * autogenerated from ROS message description language.
 * TODO: message generator implementation.
 ***/
contract StdString is Message {
    string public data;
    function StdString(string _data) {
        data = _data;
    }
}

contract SimplePub is ROSCompatible {
    Publisher      myPub;
    
    function SampleContract() {
        // Create a new publisher by topic name and type
        myPub = newPublisher('/hello', 'std_msgs/String');
    }

    function echo(string str) {
        // Publish new message by received string
        myPub.publish(new StdString(str));
    }
}
